// SPDX-License-Identifier: GPL-3.0-or-later

/**
 * Pure transforms for the declarative format generator.
 *
 * `scripts/gen-formats.ts` is the thin CLI that reads /formats/*.json, calls
 * these functions, and writes the results. Keeping the logic here (no file I/O)
 * makes it unit-testable and lets `generated-up-to-date.test.ts` re-run the
 * transforms in memory to detect drift.
 */

import type {
  FormatSpec,
  FormatRender,
  TokenizeLineKind,
  ColumnScalarType,
} from '../src/shared/formatSpec';

const TM_SCHEMA = 'https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json';
const DEFAULT_WORD_PATTERN = '[A-Za-z0-9_]+';
const VALID_RULE_IDS = new Set(['minColumns', 'column', 'coordinatePair', 'strand']);

export interface TmRule {
  name?: string;
  match?: string;
  captures?: Record<string, { name: string }>;
  patterns?: { include: string }[];
}

export interface TmGrammar {
  $schema: string;
  name: string;
  scopeName: string;
  patterns: { include: string }[];
  repository: Record<string, TmRule>;
}

/** Format key = languageId without the "omics-" prefix, e.g. "chrom-sizes". */
export function formatKey(spec: FormatSpec): string {
  return spec.identity.languageId.replace(/^omics-/, '');
}

/** Stable serialization shared by the CLI and the drift test: 2-space JSON + trailing newline. */
export function serialize(value: unknown): string {
  return JSON.stringify(value, null, 2) + '\n';
}

function columnRegex(type: ColumnScalarType, delimiter: 'tab' | 'whitespace'): string {
  switch (type) {
    case 'int':
      return '[0-9]+';
    case 'number':
      return '[0-9eE.+-]+';
    case 'string':
    default:
      return delimiter === 'tab' ? '[^\\t]+' : '\\S+';
  }
}

function suffixCaptures(
  captures: Record<string, string>,
  suffix: string,
): Record<string, { name: string }> {
  const out: Record<string, { name: string }> = {};
  for (const [idx, scope] of Object.entries(captures)) {
    out[idx] = { name: `${scope}.${suffix}` };
  }
  return out;
}

function lineKindToRule(kind: TokenizeLineKind, delimiter: 'tab' | 'whitespace', suffix: string): TmRule {
  if (kind.kind === 'regex') {
    return { match: kind.match, captures: suffixCaptures(kind.captures, suffix) };
  }
  const sep = delimiter === 'tab' ? '\\t' : '\\s+';
  const body = kind.columns.map((c) => `(${columnRegex(c.type, delimiter)})`).join(sep);
  const trailing = kind.trailing === 'optional-extra' ? `(${sep}.+)?` : '';
  const captures: Record<string, { name: string }> = {};
  kind.columns.forEach((c, i) => {
    captures[String(i + 1)] = { name: `${c.scope}.${suffix}` };
  });
  return { match: `^${body}${trailing}$`, captures };
}

/** Generate a TextMate grammar object from a spec's `tokenize` block. */
export function specToGrammar(spec: FormatSpec): TmGrammar {
  const suffix = formatKey(spec);
  const { tokenize } = spec;
  const patterns: { include: string }[] = [];
  const repository: Record<string, TmRule> = {};

  if (tokenize.comment) {
    patterns.push({ include: '#comment' });
    repository.comment = {
      name: `${tokenize.comment.scope}.${suffix}`,
      match: tokenize.comment.match,
    };
  }

  for (const kind of tokenize.lineKinds) {
    patterns.push({ include: `#${kind.name}` });
    repository[kind.name] = lineKindToRule(kind, tokenize.delimiter, suffix);
  }

  return {
    $schema: TM_SCHEMA,
    name: spec.identity.displayName,
    scopeName: spec.identity.scopeName,
    patterns,
    repository,
  };
}

/** Generate a VS Code language-configuration object from a spec's identity block. */
export function specToLangConfig(spec: FormatSpec): Record<string, unknown> {
  const cfg = spec.identity.languageConfiguration;
  const out: Record<string, unknown> = {};
  if (cfg?.lineComment) {
    out.comments = { lineComment: cfg.lineComment };
  }
  out.wordPattern = cfg?.wordPattern ?? DEFAULT_WORD_PATTERN;
  if (cfg?.brackets && cfg.brackets.length > 0) {
    out.brackets = cfg.brackets;
  }
  return out;
}

function sortedByLanguageId(specs: FormatSpec[]): FormatSpec[] {
  return [...specs].sort((a, b) => a.identity.languageId.localeCompare(b.identity.languageId));
}

function stripSchema(spec: FormatSpec): FormatSpec {
  const { $schema, ...rest } = spec as FormatSpec & { $schema?: string };
  void $schema;
  return rest as FormatSpec;
}

/** Generate the src/shared/generatedFormats.ts module source. */
export function specsToModule(specs: FormatSpec[]): string {
  const clean = sortedByLanguageId(specs).map(stripSchema);
  const banner =
    '// SPDX-License-Identifier: GPL-3.0-or-later\n' +
    '// AUTO-GENERATED by scripts/gen-formats.ts from /formats/*.json. Do not edit.\n' +
    '// Run `npm run gen:formats` to regenerate.\n\n';
  const importLine = "import type { FormatSpec } from './formatSpec';\n\n";
  return `${banner}${importLine}export const GENERATED_FORMATS: FormatSpec[] = ${JSON.stringify(clean, null, 2)};\n`;
}

function activationLanguageId(event: string): string {
  return event.startsWith('onLanguage:') ? event.slice('onLanguage:'.length) : '';
}

/**
 * Idempotently merge declarative format contributions into a parsed package.json.
 * Existing entries for non-declarative languageIds are left untouched; entries for
 * declarative languageIds are removed and re-added, so re-running is a no-op.
 * Does not mutate the input.
 */
export function mergePackageJson<T extends Record<string, any>>(pkg: T, specs: FormatSpec[]): T {
  const clone: any = JSON.parse(JSON.stringify(pkg));
  const ids = new Set(specs.map((s) => s.identity.languageId));
  const contributes = (clone.contributes ??= {});

  contributes.languages = (contributes.languages ?? []).filter((l: any) => !ids.has(l.id));
  contributes.grammars = (contributes.grammars ?? []).filter((g: any) => !ids.has(g.language));
  clone.activationEvents = (clone.activationEvents ?? []).filter(
    (e: string) => !ids.has(activationLanguageId(e)),
  );

  for (const spec of sortedByLanguageId(specs)) {
    const key = formatKey(spec);
    const { identity } = spec;
    const lang: Record<string, unknown> = {
      id: identity.languageId,
      aliases: identity.aliases,
      extensions: identity.extensions,
    };
    if (identity.filenames && identity.filenames.length > 0) lang.filenames = identity.filenames;
    if (identity.firstLine) lang.firstLine = identity.firstLine;
    lang.configuration = `./language-configuration/generated/${key}.language-configuration.json`;
    contributes.languages.push(lang);

    contributes.grammars.push({
      language: identity.languageId,
      scopeName: identity.scopeName,
      path: `./syntaxes/generated/${key}.tmLanguage.json`,
    });

    clone.activationEvents.push(`onLanguage:${identity.languageId}`);
  }

  return clone;
}

/** Structurally validate an unknown value as a FormatSpec. Returns a list of error messages (empty = valid). */
export function validateSpec(raw: unknown): string[] {
  const errors: string[] = [];
  const push = (msg: string) => errors.push(msg);

  if (typeof raw !== 'object' || raw === null) {
    return ['spec must be an object'];
  }
  const spec = raw as Record<string, any>;

  if (spec.specVersion !== 1) push('specVersion must be 1');

  const id = spec.identity;
  if (typeof id !== 'object' || id === null) {
    push('identity is required');
  } else {
    if (typeof id.languageId !== 'string' || !/^omics-[a-z0-9-]+$/.test(id.languageId)) {
      push('identity.languageId must match /^omics-[a-z0-9-]+$/');
    }
    if (typeof id.displayName !== 'string' || id.displayName.length === 0) {
      push('identity.displayName is required');
    }
    if (typeof id.scopeName !== 'string' || !/^source\./.test(id.scopeName)) {
      push('identity.scopeName must start with "source."');
    }
    if (!Array.isArray(id.extensions) || id.extensions.length === 0) {
      push('identity.extensions must be a non-empty array');
    }
  }

  const tok = spec.tokenize;
  if (typeof tok !== 'object' || tok === null) {
    push('tokenize is required');
  } else {
    if (tok.delimiter !== 'tab' && tok.delimiter !== 'whitespace') {
      push('tokenize.delimiter must be "tab" or "whitespace"');
    }
    if (!Array.isArray(tok.lineKinds) || tok.lineKinds.length === 0) {
      push('tokenize.lineKinds must be a non-empty array');
    }
  }

  const val = spec.validate;
  if (typeof val !== 'object' || val === null || !Array.isArray(val.rules)) {
    push('validate.rules must be an array');
  } else {
    val.rules.forEach((rule: any, i: number) => {
      const where = `validate.rules[${i}]`;
      if (!VALID_RULE_IDS.has(rule?.id)) push(`${where}.id must be one of ${[...VALID_RULE_IDS].join(', ')}`);
      if (typeof rule?.code !== 'string' || rule.code.length === 0) push(`${where}.code is required`);
      if (typeof rule?.message !== 'string' || rule.message.length === 0) push(`${where}.message is required`);
      if (typeof rule?.spec !== 'object' || rule.spec === null || typeof rule.spec.href !== 'string') {
        push(`${where}.spec.href is required`);
      }
    });
  }

  const render = spec.render;
  if (typeof render !== 'object' || render === null) {
    push('render is required');
  } else {
    if (render.renderer !== 'table') push('render.renderer must be "table"');
    if (!Array.isArray(render.columns) || render.columns.length === 0) {
      push('render.columns must be a non-empty array');
    }
  }

  return errors;
}

export interface ExistingRegistry {
  languageIds: string[];
  extensions: string[];
  scopeNames: string[];
}

/**
 * Detect declarative specs that would shadow an existing (hand-written) format or
 * collide with each other. Returns a list of error messages (empty = no collisions).
 */
export function findCollisions(specs: FormatSpec[], existing: ExistingRegistry): string[] {
  const errors: string[] = [];
  const seenLang = new Set(existing.languageIds);
  const seenScope = new Set(existing.scopeNames);
  const seenExt = new Set(existing.extensions);

  for (const spec of specs) {
    const { languageId, scopeName, extensions } = spec.identity;
    if (seenLang.has(languageId)) {
      errors.push(`languageId "${languageId}" collides with an existing format`);
    } else {
      seenLang.add(languageId);
    }
    if (seenScope.has(scopeName)) {
      errors.push(`scopeName "${scopeName}" (from ${languageId}) collides with an existing format`);
    } else {
      seenScope.add(scopeName);
    }
    for (const ext of extensions) {
      if (seenExt.has(ext)) {
        errors.push(`extension "${ext}" (from ${languageId}) collides with an existing format`);
      } else {
        seenExt.add(ext);
      }
    }
  }

  return errors;
}

export type { FormatSpec, FormatRender };
